AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'bin/**/*'
Style/ClassAndModuleChildren:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/EndOfLine:
  EnforcedStyle: lf
Metrics/MethodLength:
  Max: 20
Metrics/CyclomaticComplexity:
  Max: 10