env:
    RAILS_ENV: production
    REGISTRY: ghcr.io

on:
    workflow_call:
        inputs:
            tag:
                required: true
                type: string
            image_name:
                required: true
                type: string
            runner:
                required: true
                type: string
        secrets:
            DATABASE_URL:
                required: true
            JWT_SECRET:
                required: true
            SECRET_KEY_BASE:
                required: true

jobs:
    build-docker:
        runs-on: ${{ inputs.runner }}
        permissions:
            contents: read
            packages: write
        env:
            DATABASE_URL: ${{ secrets.DATABASE_URL }}
            JWT_SECRET: ${{ secrets.JWT_SECRET }}
            SECRET_KEY_BASE: ${{ secrets.SECRET_KEY_BASE }}
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2
            - name: Log in to the Container registry
              uses: docker/login-action@v2.1.0
              with:
                  username: ${{ github.actor }}
                  registry: ${{ env.REGISTRY }}
                  password: ${{ github.token }}
            - name: Extract metadata (tags, labels) for Docker
              id: meta
              uses: docker/metadata-action@v4.3.0
              with:
                  images: ${{ env.REGISTRY }}/${{ inputs.image_name }}
            - name: Build and push Docker image
              uses: docker/build-push-action@v4
              with:
                  context: .
                  push: true
                  tags: '${{ env.REGISTRY }}/${{ inputs.image_name }}:${{ inputs.tag }}'
                  labels: ${{ steps.meta.outputs.labels }}
                  cache-from: type=gha
                  cache-to: type=gha,mode=max
