on:
    push:
        branches:
            - main

env:
    RAILS_ENV: production
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{ github.repository }}
jobs:
    migrate:
        runs-on: ubuntu-latest
        env:
            DATABASE_URL: ${{ secrets.DATABASE_URL }}
            SECRET_KEY_BASE: ${{ secrets.SECRET_KEY_BASE }}
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            - name: Install Ruby dependencies
              uses: ruby/setup-ruby@v1
              with:
                  bundler-cache: true
            - name: Migrate databases
              run: bin/rails db:migrate

    pre-deploy:
        runs-on: ubuntu-latest
        needs: migrate
        env:
            DATABASE_URL: ${{ secrets.DATABASE_URL }}
            JWT_SECRET: ${{ secrets.JWT_SECRET }}
            SECRET_KEY_BASE: ${{ secrets.SECRET_KEY_BASE }}
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            - name: Install Ruby dependencies
              uses: ruby/setup-ruby@v1
              with:
                  bundler-cache: true
            - name: Install Node dependencies
              uses: actions/setup-node@v3
              with:
                  node-version: 18
            - name: Precompile assets
              run: bundle exec rake assets:precompile
            - name: Clean assets
              run: bundle exec rake assets:clean

    build-docker:
        runs-on: ARM64
        permissions:
            contents: read
            packages: write
        needs: pre-deploy
        env:
            DATABASE_URL: ${{ secrets.DATABASE_URL }}
            JWT_SECRET: ${{ secrets.JWT_SECRET }}
            SECRET_KEY_BASE: ${{ secrets.SECRET_KEY_BASE }}
            CAPROVER_APP: ${{ secrets.APP_NAME }}
            APP_TOKEN: ${{ secrets.APP_TOKEN }}
            CAPROVER_HOST: ${{ secrets.CAPROVER_SERVER }}
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2
            - name: Log in to the Container registry
              uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
            - name: Extract metadata (tags, labels) for Docker
              id: meta
              uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
              with:
                  images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
            - name: Build and push Docker image
              uses: docker/build-push-action@v4
              with:
                  context: .
                  push: true
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}
                  cache-from: type=gha
                  cache-to: type=gha,mode=max
            - name: Deploy App to CapRover
              uses: caprover/deploy-from-github@v1.1.2
              with:
                  server: '${{ secrets.CAPROVER_SERVER }}'
                  app: '${{ secrets.APP_NAME }}'
                  token: '${{ secrets.APP_TOKEN }}'
                  image: '${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:main'
